### ISSUE TITLE
`NameError: name 'idReturn' is not defined` when attempting to start a Halcyon-based bot after a small amount of use

### ISSUE THREAD

**Issue by jeffcasavant** [WesR/Halcyon#1]
I am running halcyon-stock-bot.  I invited it to one room to tested it (it sent its welcome message and responded to a ticker symbol).  I invited it to another and it joined and then crashed with a traceback similar to this one.  It did not send its welcome message.  I restarted the bot process and it's now always producing the following traceback:

```
Traceback (most recent call last):
    File "/app/bot.py", line 63, in <module>
        client.run(halcyonToken=keys["halcyon"], longPollTimeout=1)#make sure you set it back to 30sec once your done debugging
    File "/usr/local/lib/python3.10/site-packages/halcyon/halcyon.py", line 482, in run
        self._roomcacheinit()
    File "/usr/local/lib/python3.10/site-packages/halcyon/halcyon.py", line 119, in _roomcacheinit
        self.roomCache["rooms"][roomID] = room(rawEvents=self.restrunner.getRoomState(roomID), roomID=roomID)
    File "/usr/local/lib/python3.10/site-packages/halcyon/room.py", line 81, in __init__
        self.predecessor = self.roomPredecessor(event["content"].get("predecessor"))
    File "/usr/local/lib/python3.10/site-packages/halcyon/room.py", line 155, in __init__
        self._parseRawContent(rawContent)
    File "/usr/local/lib/python3.10/site-packages/halcyon/room.py", line 164, in _parseRawContent
        self.event = idReturn(rawContent.get("event_id"))
NameError: name 'idReturn' is not defined
```

and failing to start.

I am running inside a docker container I built myself in Kubernetes.  That container is built from [this base dockerfile](https://github.com/jeffcasavant/public-containers/blob/master/wesr-halcyon/Dockerfile) and [this stock bot specific dockerfile](https://github.com/jeffcasavant/public-containers/blob/master/wesr-halcyon-stock-bot/Dockerfile).

Happy to provide whatever other detail you need to help troubleshoot.

**Comment by jeffcasavant** [comment]
I did base my containers on Python 3.10, in case that might be causing the issue.

**Comment by WesR** [comment]
Hey Jeff, I was able to find and solve the fix with the info you left here and on the matrix. Thanks for reporting it! Version 1.1.1 is currently building with the fix. I'll make sure to credit you!
